name: Deploy Infra

on:
  push: 
    branches:  
      - main
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS OIDC authentication
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      # Package Lambda Code Before Running Terraform (Inside terraform/ Itself)
      - name: Package Lambda Code
        run: |
          cd terraform
          zip -r lambda.zip . -x ".tf"  # Zip all files EXCEPT Terraform files
          ls -lh lambda.zip  # Debug: Check if ZIP is created

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Select Workspace & Apply
        run: |
          cd terraform
          terraform workspace select ${{ github.ref_name == 'main' && 'prod' || 'dev' }} || terraform workspace new ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
          terraform apply -auto-approve
